insert EstadoReparacion values ('SIN DETERMINAR', 'Sin Determinar','Sin determinar',1,getdate(),99)
insert marca values ('SIN DETERMINAR','Codigo de marca utilizado durante la migracion para transacciones sin marca',1,getdate(),99)
insert tipodispositivo values ('SIN DETERMINAR', 'Sin determinar',1,getdate(),99)
insert cliente values(99999999,'SIN DETERMINAR', 'SIN DETERMINAR','sindeterminar@gmail.com','SIN DETERMINAR', 'SIN DETERMINAR', 'SIN DETERMINAR',null, 'SIN DETERMINAR', null,null)
insert Comercio values('SIN DETERMINAR', null,null,null,null,null,null,null,null,1,getdate(),99)

--migrate estados
insert EstadoReparacion
select nombre, descripcion,categoria,activo,modificadoEn,modificadoPor from oldEstadoRep

--insert direccion placeholder
insert direccion
select null,RTRIM(LTRIM(direcc)),RTRIM(Ltrim(ecalle1)),ltrim(rtrim(ecalle2)),ltrim(rtrim(localidad)),null,null,null,null,null,null,getdate(),nrocli
from oldcliente

select * from direccion

--Migro clientes
insert cliente
select nrocli,
SUBSTRING(nombre,CHARINDEX(' ',nombre),LEN(nombre)),
SUBSTRING(nombre,0,CHARINDEX(' ',nombre)),
'imcompleto@email.com',
telefono,
null,
RTRIM(LTRIM(direcc)) + ' entre ' + RTRIM(Ltrim(ecalle1)) + ' y ' + ltrim(rtrim(ecalle2)) + ', ' + ltrim(rtrim(localidad))
,(select top 1 direccionid from direccion where changedby = nrocli)
,null,null,null
from oldcliente

--Migro respobsables y tecnicos a usuarios
insert Usuario values ('MAXI','maxi.fastservice@gmail.com','MAXI','DANERI','daneri','','','',1)
insert Usuario values ('sinasignar@gmail.com','SIN ASIGNAR','SIN ASIGNAR','SIN ASIGNAR','SIN ASIGNAR','84123124','','',1)

select * from Usuario

insert usuario 
select 
SUBSTRING(nombre,0,CHARINDEX(' ',nombre)),
SUBSTRING(nombre,0,CHARINDEX(' ',nombre)) + '@gmail.com',
SUBSTRING(nombre,0,CHARINDEX(' ',nombre)),
SUBSTRING(nombre,CHARINDEX(' ',nombre),LEN(nombre)),
'123456',
nrotec,
'',
null,
0
from oldtecnico
union
select 
SUBSTRING(nombre,0,CHARINDEX(' ',nombre)),
SUBSTRING(nombre,0,CHARINDEX(' ',nombre)) + '@gmail.com',
SUBSTRING(nombre,0,CHARINDEX(' ',nombre)),
SUBSTRING(nombre,CHARINDEX(' ',nombre),LEN(nombre)),
'123456',
nrores,
'',
null,
0
from  oldresponsable

--grant access to tecnicos
insert UsuarioRol
values ((SELECT top 1 Rolid from Role where Nombre = 'Tecnico'),(select top 1 UserId from Usuario where Nombre = 'ROBERTO' and ltrim(rtrim(Apellido)) = 'ARROYO'))

insert UsuarioRol
values ((SELECT top 1 Rolid from Role where Nombre = 'Tecnico'),(select top 1 UserId from Usuario where Nombre = 'JUAN' and Apellido = ' KLICHUK'))

insert UsuarioRol
values ((SELECT top 1 Rolid from Role where Nombre = 'Tecnico'),(select top 1 UserId from Usuario where Nombre = 'JAVIER' and Apellido = ''))

insert UsuarioRol
values ((SELECT top 1 Rolid from Role where Nombre = 'Gerente'),(select top 1 UserId from Usuario where Nombre = 'LUIS' and Apellido = ''))

insert UsuarioRol
values ((SELECT top 1 Rolid from Role where Nombre = 'Tecnico'),(select top 1 UserId from Usuario where Nombre = 'LUIS' and Apellido = ''))

--activate current users
update Usuario 
set Activo = 1 
where (Nombre = 'ROBERTO' and ltrim(rtrim(Apellido)) = 'ARROYO') 
or (Nombre = 'JUAN' and ltrim(rtrim(Apellido)) = 'KLICHUK')
or (Nombre = 'JAVIER' and ltrim(rtrim(Apellido)) = '')
or (Nombre = 'LUIS' and ltrim(rtrim(Apellido)) = '')
or (Nombre = 'MAXI' and ltrim(rtrim(Apellido)) = 'DANERI')

--update maxi a Admin
update UsuarioRol
set RolId = 3
where userid = 1

update Usuario 
set Contraseña = 'arroyo'
where (Nombre = 'ROBERTO' and ltrim(rtrim(Apellido)) = 'ARROYO') 

update Usuario 
set Contraseña = 'praderanandu'
where (Nombre = 'LUIS' and ltrim(rtrim(Apellido)) = '')

update Usuario 
set Contraseña = 'daneri'
where (Nombre = 'MAXI' and ltrim(rtrim(Apellido)) = 'DANERI')

update Usuario 
set Contraseña = 'klichuk'
where (Nombre = 'JUAN' and ltrim(rtrim(Apellido)) = 'KLICHUK')

if (db_name() = 'FastService-Test')
begin	
	update Usuario 
	set Contraseña = 'prueba'
	where (Nombre = 'ROBERTO' and ltrim(rtrim(Apellido)) = 'ARROYO') 
	or (Nombre = 'JUAN' and ltrim(rtrim(Apellido)) = 'KLICHUK')
	or (Nombre = 'JAVIER' and ltrim(rtrim(Apellido)) = '')
	or (Nombre = 'LUIS' and ltrim(rtrim(Apellido)) = '')
	or (Nombre = 'MAXI' and ltrim(rtrim(Apellido)) = 'DANERI')	
end

--clean up duplicated records
if ((select 1 from tempdb.sys.tables where name like '%tokeep%') > 0)
	drop table #tokeep

create table #tokeep (timestamp varchar(20),nrotra varchar(20) )

insert #tokeep 
select MAX(timestamp), nrotra from oldtranu group by nrotra having COUNT(nrotra) > 1
union
select MAX(timestamp), nrotra from oldtranu group by nrotra having COUNT(nrotra) = 1

delete t
from oldtranu t
left join #tokeep d on t.nrotra = d.nrotra and t.timestamp = d.timestamp
where d.nrotra is null 

delete oldtranu where timestamp  =''
update oldtranu set fechacom = null where fechacom < '1800-03-22'

--Migra detalle de reparaciones
insert reparaciondetalle
select 
CASE o.garantia WHEN 'C' THEN 0 ELSE 1 END,  
CASE o.movil WHEN 0 THEN 0 ELSE 1 END,--to be determined
o.nrotra,
o.fechacom,
null,
CASE PRECIO WHEN '.00' THEN 0 ELSE SUBSTRING(PRECIO,0,CHARINDEX('.',precio)) END as precio,
getdate(),
CASE PRECIO WHEN '.00' THEN 0 ELSE SUBSTRING(PRECIO,0,CHARINDEX('.',precio)) END as presup,
modelo,
serie,
serbus,
ubicacion,
null,
null,
getdate(),
99
from oldtranu o

--Migro transacciones a reparaciones
insert reparacion
select nrotra,
ISNULL((select top 1 c.clienteid from cliente c where c.Dni = nrocli),(SELECT  top 1 clienteid from cliente where nombre = 'SIN DETERMINAR')),
ISNULL((select top 1 c.UserId from Usuario c where c.Direccion = nroemp),(select top 1 c2.userid from usuario c2 where c2.nombre = 'SIN ASIGNAR')),
ISNULL((select top 1 c.UserId from Usuario c where c.Direccion = nrotec),(select top 1 c2.userid from usuario c2 where c2.nombre = 'SIN ASIGNAR')),
ISNULL((select top 1 e.EstadoReparacionId from EstadoReparacion e where e.descripcion = nroest),(select top 1 c2.EstadoReparacionId from EstadoReparacion c2 where c2.nombre = 'SIN DETERMINAR')),
ISNULL((select top 1 c.ComercioId from Comercio c where c.telefono2 = nrocom),(select top 1 c2.ComercioId from Comercio c2 where c2.code = 'SIN DETERMINAR')),
ISNULL((select top 1 m.MarcaId from Marca m where m.descripcion = nromar),(select top 1 m2.marcaid from marca m2 where nombre = 'SIN DETERMINAR')),
ISNULL((select top 1 t.tipoDispositivoid from tipoDispositivo t where t.descripcion = nrotip),(select top 1 t2.TipoDispositivoId from tipoDispositivo t2 where t2.nombre = 'SIN DETERMINAR')),
rd.reparaciondetalleid,
null,
null,
null,
desde,
99,
desde,
99
from oldtranu o
join reparacionDetalle rd on o.nrotra = rd.nroReferencia

----Migro novedades
update oldnovedad 
set hora = 00
where (hora is null or hora ='' or hora = '' or hora = 'pp')

update oldnovedad 
set minutos = 00
where (hora is null or minutos ='' or minutos = '' or minutos = 'pp')

insert novedad 
select 
n.nrotra,
isnull((select top 1 userid from Usuario where Direccion = nrotec),(select c2.userid from usuario c2 where c2.nombre = 'SIN ASIGNAR')),
codnov,
case pesos when '' then 0 else isnull(pesos,0) end,
observ,
convert(datetime,fecha + ' ' + hora + ':' + minutos),
99
from oldnovedad n left join oldobserv o on n.transac = o.transac 
order by nrotra asc

update Marca
set activo = 0
where Nombre not in 
(
'HITACHI',
'MUSTANG',
'PHILIPS',
'GRUNDIG',
'NOBLEX',
'SAMSUNG',
'TELEFUNKEN',
'KEN BROWN',
'PANASONIC',
'SHARP',
'TALENT',
'WESTINGHOUSE',
'TONOMAC',
'PANAVOX',
'FISHER',
'PHILCO',
'TEAC',
'CROWN',
'AKAI',
'ULTRASONIX',
'SANYO',
'EPSON',
'MARSHALL',
'NATIONAL',
'DREAN',
'SERIE DORADA',
'SONY',
'ZENITH',
'JVC',
'MELODY',
'MITSUBISHI',
'RANSER',
'BGH',
'TRIDENT',
'ATTIKA',
'CASIO',
'CONTINENTAL',
'SIEMENS',
'GOLDSTAR',
'DELM',
'MAGNAVOX',
'SYLVANIA',
'SEIKO',
'AIWA',
'TOBISHI',
'SANSUI',
'SPICA',
'REPMAN',
'NEC',
'SABA',
'BAKOSONIC',
'SANSEI',
'PIONEER',
'MULTITECH',
'PANASHIBA',
'ALPINE',
'RCA',
'AUDINAC',
'TOSHIBA',
'GRAL SOUND',
'UTOPIA',
'TARGA',
'AIKO',
'PEAVEY',
'GRAL ELECTRI',
'DAEWOO',
'AUDIOLOGIC',
'MOTOROLA',
'BOSCH',
'HISHI',
'ADMIRAL',
'TEC',
'TOPHOUSE',
'PROTECH',
'CCE',
'DAIHATSU',
'AURORA',
'PYRAMID',
'SKP',
'LG',
'ATMA',
'WENSTONE',
'PROVIEW',
'H.Q.S',
'OLIVETTI',
'ELECTROLUX',
'ATMA',
'ELECT SYSTEM',
'SUZUKI',
'TCL',
'HITPLUS',
'KELVINATOR',
'GLOBAL HOME',
'PROTALIA',
'TUYU',
'HYUNDAI',
'DURABRAND',
'ILO'
)


update Comercio
set activo = 0
where code not in (
'ROEL',
'SOLANO',
'CLAYPOLE',
'SUR',
'DOGIL',
'RIKY',
'MARVIC',
'IGHUAM',
'DAMISUR',
'CASTRO',
'SPEDALES',
'ERATO',
'FARAONI',
'DUMARI',
'LA ESQ DEL C',
'MARITIMO',
'EL CHAQUENO',
'D`ASCENZO EN',
'ECONOMICA',
'TODHOGAR',
'LA 1RA SOLAN',
'GIGLIA',
'MILLAN',
'FERREYRA',
'POLICELLA',
'MARIANO',
'GRIS',
'D`ELIA',
'EL HOGAR DE',
'VARELA HOGAR',
'J D AMOBLAMI',
'D`ELIA E H.',
'ADRI-MAT-',
'PEREIRA',
'NINO',
'GLEW',
'GISMONDI',
'EVAL S.A.',
'ALBERT',
'JUAREZ CONFO',
'VARELA',
'NOVELLI',
'LA PAZ',
'CLAYPOLE HOG',
'SU AMIGO',
'CECY',
'CREDIHOGAR S',
'LOPEZ HOGAR',
'LADY',
'TABU HOGAR',
'GARIBALDI',
'CENTRAL',
'AUTOCREDITO',
'EL 28',
'LARES',
'CONTI',
'NICOLA',
'CASTELLI HOG',
'EL CONFORT D',
'EL REY DEL G',
'LOS INDIOS',
'PIDALA',
'N CASA',
'RODDEL',
'VOLCAN BERAZ',
'HOGAR LINE',
'GIUDICE GUIL',
'SCHIRO',
'RADIO JORGE',
'GINOS',
'GUSTAL',
'DOMBEL',
'EL EMPORIO D',
'JESUS',
'LUCAS HOGAR',
'VENTURI.',
'PEDRAZA.',
'RENE',
'RAFAEL',
'EL CAMINO',
'TOGNOLA OSCA',
'ORENSANA',
'POLYCHROME H',
'ELITE HOGAR',
'GERARDO',
'HECTOR HOGAR',
'GERLI HOGAR',
'MOLA',
'LA GRAN SIET',
'ITALIA',
'WAY MUSIC S.',
'LOS 2 HNOS',
'POLO',
'HECTOR',
'SINDICATO FO',
'LA CONVENIEN',
'TELEART',
'BELLONI',
'IACONO',
'FABIANO',
'25 DE MAYO',
'ALFRA',
'DEL PLATA',
'JUANJO',
'TONY',
'LIBRA',
'ALEM',
'UCHANA',
'LOZIO HOGAR',
'JULIO',
'LEGARE',
'HECTOR COPPE',
'GER-MAR MUEB',
'ERNESTO',
'MERIGGI',
'LIBERTAD 133',
'GALVAN',
'ASTORGA',
'HORIZONTE',
'STILO',
'VITULI LEONA',
'PIANICIO S.R',
'TABIERES',
'NAPOLI',
'CARDOZO HOGA',
'MAT',
'GALLIO',
'MORAN 23',
'ALDRI HOGAR',
'MAXI HOGAR',
'EUGSTER.',
'MAG-FER- CON',
'NELSON',
'COSI HUGO',
'LENG ROBERTS',
'CARREFOUR',
'NOBILE',
'DEL CAMPO',
'PADRINO',
'MICROSPORT',
'GICO',
'JUMBO',
'LOKEV',
'TABY',
'MARIANA HOGA',
'OLIVARI.',
'EL IMPULSO',
'KUKA',
'PRIMOS',
'VICTOR',
'NOVIDEAS.',
'RODO',
'ELECT.CONFO',
'MAN',
'PEROZZI',
'WATSON',
'ORIENTE',
'SERGIMAR',
'LUSION',
'KITAY HOGAR',
'KAIRO',
'BARBATO HOGA',
'FERROVAL S.R',
'LA LLAVE DEL',
'EZPE SUR',
'AYELEN',
'VEGA CONFORT',
'FLOPY HOGAR',
'CALEGARI',
'KIENASC',
'LA NOCHE DEL',
'ORANIAS',
'OZORES.',
'MARMOL CONFO',
'SANTAYA',
'CALCHAQUI HO',
'COOP. DE CRE',
'BLANCA',
'CHIYAMA HOGA',
'DEL CONFORT',
'THELGRO',
'CONCERTOS',
'SANILUX',
'ENRIQUE',
'VICTOR PARDO',
'DICK',
'FRAVEGA',
'AMTRAS',
'HECTOR PEREZ',
'CHACABUCO HO',
'COPROGAR',
'CADIA',
'PICAPIEDRA',
'23 HOGAR',
'EXQUIT.',
'ALSINA.',
'PICO',
'MUSIMUNDO',
'MARIO HOGAR',
'EL COLONIAL',
'ROMINA',
'A.M.T.A.E.',
'ZAPIOLA',
'CLAUDIO',
'BLAUSTE',
'INVER-HOME-',
'PONSA',
'ALFI',
'CREDI-HOGAR',
'ECOMAX.S.A.',
'BUSSA HOGAR',
'ZACCARO D.',
'MARTI',
'IND.TOTAL',
'ENGELS',
'ZURLO',
'FELIUX',
'2000',
'SODANO',
'MARCHESE ANA',
'LA CASONA',
'ARIES.',
'BRESIN',
'X MAYOR S.A.',
'FLORENTIN',
'TARANTO ONOF',
'MANFER TV',
'CENTENARIO',
'TARANTO JUAN',
'BRUMEC JUAN',
'BRUMEC M',
'CAIRO',
'KEMPF JACOBO',
'INTERBENE EL',
'CONTE',
'MUTUAL.',
'RASETTI',
'CABILDO',
'DE SETA',
'MARAIA',
'MONELOS',
'DINOGAR',
'MAROTTE',
'DISCAL',
'ESPORA',
'VICTOR',
'OBDULIO',
'SOLANO',
'GIFER',
'HORIZONTE',
'MUNOZ',
'CHICAGO',
'MADERA',
'MILNA',
'MAKS',
'RACHEL',
'PICCINI',
'SANDRA',
'PREFECTURA',
'GUIDO',
'HIGH',
'AUDIO CENTRO',
'KITAI',
'BLANCA',
'HENRY HOGAR',
'CENTRO',
'PENNACINO',
'JOLI',
'MIGUEL',
'ESTELA',
'FAX',
'MENA',
'CARO',
'GUTIERREZ',
'FREEPORT',
'TUCUMANO',
'BUFFA',
'QUINTANA',
'SANDRA SPORT',
'LINDAS',
'ROMEO',
'GISELL',
'ROBERT',
'BOEDO',
'MANTI',
'PABLO',
'HOGAR',
'OSCAR',
'CROWN MUST.',
'NORTE',
'MALVINAS',
'ACUARIO',
'LATERRA',
'BERAZATEGUI',
'CONFORT-ME-',
'ENTREVATIX',
'CORAL',
'VERNOE',
'SOL',
'SONI',
'IDEAL',
'AVELLANEDA',
'CABEZAS',
'ANA',
'H.M.',
'SCIOCCO',
'LA MUEB.',
'EL SOL',
'LUDOVICO',
'FLOP',
'ABADIAS',
'CARINA',
'SERGIO',
'HUDSON',
'PASCO',
'MAKRO',
'FRESSAN',
'GABRIEL',
'CHANNEL',
'MG.',
'MANCI',
'ANDREA',
'MARENA',
'RAQUEL',
'GRANIEL',
'TROZZI',
'APOLO',
'A.T.',
'EL REY',
'DEL VESTIR',
'ZITO',
'BRUGALETA',
'LAS COLONIAS',
'LA ESPERANZA',
'DANI HOGAR',
'FLORENCIA',
'LOS NIETO',
'MAYA',
'MARZAN',
'DAGAR',
'GERLI HOGAR',
'NIC',
'ADRI-MAR-',
'LA BOLSA',
'LOUVRE HOGAR',
'SUPER',
'ANGELA HOGAR',
'LA FLORIDA',
'LOS AMIGOS',
'VICTOR',
'CITY',
'GERARDO',
'BLANCA',
'RENO',
'CAMANO',
'NICOLAS',
'MALMO',
'PUPIS HOGAR',
'NIVEL 5',
'HENRRY HOGAR',
'TORTI',
'POL',
'MOHAMED',
'BYNON',
'YANNI',
'TOTAL',
'MANDRILE',
'MUSIMUNDO',
'SUPERGAL',
'ROMINA',
'BALANZAS',
'DE ARCO',
'CENTER',
'AL-MAR',
'TOTI',
'ARGENTINO',
'VARELA',
'BIOGRAFO',
'GIBER',
'CISNE',
'DAPAS',
'GARCIA',
'TROZZI',
'CENTRAL',
'ARTIGA',
'CJ',
'AVELLANEDA',
'BENITEZ',
'COTO',
'PIRINCHOS',
'GRACIELA',
'D`ASCENZO',
'MOSCONI',
'PUPIS',
'LACOLA',
'MATIAS',
'EL 26',
'AGUIRRE',
'HERNAN',
'EMMANUEL',
'MONTEGROSSO',
'IRIS',
'MAR-ZI',
'NIKCER',
'COPROGAR',
'EASY',
'MONTALBANO',
'AMERICANA',
'CREDITO HOGA',
'FACCONE',
'GARBARINO',
'MI SUENO',
'FRANCESCHI',
'ENCUENTRO',
'ROMINA',
'JULIO',
'HL',
'SUR',
'ARIAS',
'DISTRISUNG',
'KANDY',
'VIVIR',
' PRIMOS',
'LUCA',
'HUGUITO',
'AUCHAN',
'4284-3259',
'CARBONAZO',
'EL ARCA DE',
'BIOGRAFO',
'DEL PLATA',
'VENTURA',
'SA SA',
'SELECTOGAR',
'SAPIENZA',
'COOPERATIVA',
'TELECOMPRAS',
'CARLOS',
'ARIAS',
'ARIEL',
'PORTILLO',
'OPTICA',
'ARIAN',
'LEVY',
'VICTORIA',
'SHOP',
'MINOTTI',
'HUDSON',
'LIBRA',
'ITALCRED',
'9 DE JULIO',
'PABLO',
'EKONO',
'BOSSI',
'MARIO',
'LOPEZ',
'RECEPTORIA',
'CURVA',
'LA GUARDA',
'MEGATONE',
'F.M',
'KING',
'HUGO',
'DON JUAN',
'NUEVO',
'Elektra',
'VICTOR',
'acuario',
'EL DORADO',
'FLORIS',
'SUAREZ',
'RIVAS',
'pari',
'SKULD',
'miguel',
'MAGA',
'COPPEL',
'CACHORRO',
'SIN DETERMINAR')

update TipoDispositivo
set activo = 1
where nombre not in (
'CENTRO MUSIC',
'AUTO.ST.',
'TVC',
'C REM',
'AUDIO',
'MULTIPLICADO',
'MEZCLADOR',
'STEREO',
'DECK',
'BAFLE',
'MICROFONO',
'CONSOLA',
'PLANCHA',
'TOSTADOR',
'LICUADORA',
'BATIDORA',
'TELEFONO',
'EXPRIMIDOR',
'RADIADOR ELE',
'CAFETERA',
'JUGUERA',
'MICROONDA',
'MONITOR',
'VENTILADOR',
'DVD',
'POTENCIA',
'HOMETHEATER',
'HORNO ELECT',
'LUSTRA ASPIR',
'ESTUFA',
'CALOVENTOR',
'SPEAKER SYST',
'LCD',
'LED TV',
'BLU-RAY',
'NOTEBOOKS',
'PAVA ELECTR',
'SOUP MORE',
'TABLET',
'DVD PORTATIL',
'ASPIRADORA',
'panificadora',
'proyector')