//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int CompraId { get; set; }
        public int ProveedorId { get; set; }
        public decimal Monto { get; set; }
        public Nullable<int> FacturaId { get; set; }
        public int PuntoDeVentaId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Comprador { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual PuntoDeVenta PuntoDeVenta { get; set; }
    }
}
