//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.Pago = new HashSet<Pago>();
        }
    
        public int CompraId { get; set; }
        public string ProveedorId { get; set; }
        public decimal Monto { get; set; }
        public string Descripcion { get; set; }
        public int PuntoDeVentaId { get; set; }
        public int Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CreadoPor { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual PuntoDeVenta PuntoDeVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
    }
}
