//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprasAPagar
    {
        public int CompraId { get; set; }
        public string ProveedorId { get; set; }
        public decimal Monto { get; set; }
        public string Descripcion { get; set; }
        public int PuntoDeVentaId { get; set; }
        public int Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CreadoPor { get; set; }
        public decimal saldo { get; set; }
    }
}
