//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.Pago = new HashSet<Pago>();
        }
    
        public int CompraId { get; set; }
        public int ProveedorId { get; set; }
        public decimal Monto { get; set; }
        public Nullable<int> FacturaId { get; set; }
        public int PuntoDeVentaId { get; set; }
        public int Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string CreadoPor { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual PuntoDeVenta PuntoDeVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
    }
}
