//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FastServiceEntities : DbContext
    {
        public FastServiceEntities()
            : base("name=FastServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<PuntoDeVenta> PuntoDeVenta { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
    }
}
