//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo
    {
        public int DispositivoModeloId { get; set; }
        public Nullable<int> MarcaId { get; set; }
        public Nullable<int> TipoId { get; set; }
        public string Modelo1 { get; set; }
        public string Code { get; set; }
        public string Descripcion { get; set; }
        public byte[] activo { get; set; }
        public Nullable<System.DateTime> modificadoEn { get; set; }
        public Nullable<int> modificadoPor { get; set; }
    }
}
