//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class oldcliente
    {
        public Nullable<int> nrocli { get; set; }
        public string nombre { get; set; }
        public string direcc { get; set; }
        public string ecalle1 { get; set; }
        public string ecalle2 { get; set; }
        public string localidad { get; set; }
        public Nullable<int> nroloc { get; set; }
        public string categoria { get; set; }
        public string observ { get; set; }
        public string telefono { get; set; }
        public string vinopor { get; set; }
    }
}
