//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int PagoId { get; set; }
        public int CompraId { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaDebito { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string NroReferencia { get; set; }
        public string Motivo { get; set; }
        public int TipoTransaccionId { get; set; }
        public Nullable<int> FacturaId { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int MetodoDePagoId { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual MetodoPago MetodoPago { get; set; }
        public virtual TipoTransaccion TipoTransaccion { get; set; }
    }
}
