//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int PagoId { get; set; }
        public int CompraId { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaDebito { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string NroReferencia { get; set; }
        public string Motivo { get; set; }
    
        public virtual Compra Compra { get; set; }
    }
}
