//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reparacion
    {
        public int ReparacionId { get; set; }
        public int ClienteId { get; set; }
        public int EmpleadoAsignadoId { get; set; }
        public int TecnicoAsignadoId { get; set; }
        public int EstadoReparacionId { get; set; }
        public Nullable<int> ComercioId { get; set; }
        public int MarcaId { get; set; }
        public int TipoDispositivoId { get; set; }
        public Nullable<int> ReparacionDetalleId { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<System.DateTime> InformadoEn { get; set; }
        public Nullable<int> InformadoPor { get; set; }
        public System.DateTime ModificadoEn { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
        public System.DateTime CreadoEn { get; set; }
        public Nullable<int> CreadoPor { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Comercio Comercio { get; set; }
        public virtual EstadoReparacion EstadoReparacion { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ReparacionDetalle ReparacionDetalle { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual TipoDispositivo TipoDispositivo { get; set; }
        public virtual TipoDispositivo TipoDispositivo1 { get; set; }
    }
}
