//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMenu
    {
        public int id { get; set; }
        public int RolId { get; set; }
        public int ItemMenuId { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ItemMenu ItemMenu { get; set; }
    }
}
