//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMenu
    {
        public int id { get; set; }
        public int RolId { get; set; }
        public int ItemMenuId { get; set; }
    
        public virtual ItemMenu ItemMenu { get; set; }
        public virtual Role Role { get; set; }
    }
}
