//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoNovedad
    {
        public int TipoNovedadId { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> activo { get; set; }
        public string modificadoPor { get; set; }
        public Nullable<System.DateTime> modificadoEn { get; set; }
    }
}
