//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int VentaId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public decimal Monto { get; set; }
        public bool Facturado { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> FacturaId { get; set; }
        public string RefNumber { get; set; }
        public int PuntoDeVentaId { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Vendedor { get; set; }
        public Nullable<int> MetodoPagoId { get; set; }
        public int TipoTransaccionId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual PuntoDeVenta PuntoDeVenta { get; set; }
        public virtual PuntoDeVenta PuntoDeVenta1 { get; set; }
        public virtual TipoTransaccion TipoTransaccion { get; set; }
    }
}
