//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ComprasAPagar
    {
        public int CompraId { get; set; }
        public string ProveedorId { get; set; }
        public decimal Monto { get; set; }
        public bool Facturado { get; set; }
        public string Descripcion { get; set; }
        public int PuntoDeVentaId { get; set; }
        public int Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CreadoPor { get; set; }
        public decimal saldo { get; set; }
    }
}
