name: Deploy FastService Web App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: fastserviceweb    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root

jobs:
  build_and_deploy:
  
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@master  
    
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      
    - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
      run: nuget restore
    
    - name: Run MSBuild
      run: msbuild FastService.sln
    
    - name: Azure Login
      uses: Azure/login@v1
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
      # Name of the Azure Web App
        app-name: ${{ env.AZURE_WEBAPP_NAME}}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/FastService/'
